server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: iss-config-server
          uri: https://github.com/SantiagoISC/microservicios
          search-paths: config-data
  application:
    name: config-service
